name: 添加收藏
description: 添加一个新的收藏项目
title: "[收藏] "
labels: ["待分类"]
body:
  - type: markdown
    attributes:
      value: |
        ## 添加收藏
        请填写以下信息以添加一个新的收藏项目。
        
  - type: input
    id: url
    attributes:
      label: 链接
      description: 收藏项目的URL
      placeholder: "https://example.com"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 简要描述为什么收藏这个项目
      placeholder: "这个工具可以帮助..."
    validations:
      required: false
      
  - type: dropdown
    id: tags
    attributes:
      label: 标签
      description: 选择适合的标签（可多选）
      multiple: true
      options:
        - 网站
        - 工具
        - 文章
        - 视频
        - 书籍
        - 开发
        - 教程
        - 设计
        - 效率
        - 前端
        - 后端
        - AI
        - 移动
        - 算法
        - 学习
        - 其他
    validations:
      required: true
      
  - type: input
    id: custom_tags
    attributes:
      label: 自定义标签
      description: 如需添加其他标签，请用逗号分隔
      placeholder: "标签1,标签2,标签3"
    validations:
      required: false 