name: 添加收藏
description: 添加一个新的收藏项目
title: "[收藏] "
labels: ["favorites"]
body:
  - type: markdown
    attributes:
      value: |
        ## 添加收藏
        请填写以下信息以添加一个新的收藏项目。
        
  - type: input
    id: url
    attributes:
      label: 链接
      description: 收藏项目的URL
      placeholder: "https://example.com"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 简要描述为什么收藏这个项目
      placeholder: "这个工具可以帮助..."
    validations:
      required: false
      
  - type: dropdown
    id: tags
    attributes:
      label: 标签
      description: 选择适合的标签（可多选）
      multiple: true
      options:
        - 工具
        - 文章
        - 设计
        - AI
        - 学习
        - 常用
        - 其他
    validations:
      required: true